### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [oertl/hyperloglog-sketch-estimation-paper#3]
Hi:
what would be the license for your code?
Thanks!

**Comment by oertl** [comment]
I do not intend to license the code. I have published the code to allow reproducing the results presented in my research paper.

**Comment by pombredanne** [comment]
@oertl 

This is a pretty weird statement... by virtue of the GitHub ToS and posting it publicly, your code is already licensed. So unless you want it under a license that may not be to your advantage, the lack of an explicit license by you is likely something that is to your detriment. It is even more confusing because your code depends on open source and licensed code.

**Comment by oertl** [comment]
Please, see https://choosealicense.com/no-license/. By accepting GitHub ToS I allow viewing and forking the repository, but AFAIK nothing else.

**Comment by pombredanne** [comment]
I know about this, and https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users is the authoritative current text that GitHub may change at any time FWIW. Using explicit clarity would be best for everyone IMHO rather than relying on modifiable terms set by others. But's that your call. May be you do not care nor want your code to be re-used.

Cordially
