### ISSUE TITLE
A better citation than arXiv?

### ISSUE THREAD

**Issue by j2kun** [oertl/hyperloglog-sketch-estimation-paper#5]
Hi there!

I read through your wonderful paper, which I discovered because of the reference to it in the [Redis source code](https://github.com/redis/redis/blob/d96f47cf06b1cc24b82109e0e87ac5428517525a/src/hyperloglog.c) (of course, you know this because you wrote it in https://github.com/redis/redis/commit/1e9a7748716e1cd234893dd858d07ffa77920e41#diff-d2bbaa446905d084e2b9d0bb10b299bb87a465a7cdfd95768aa2d320db357dc2). I am surprised that your improved estimator is not more well known among sketching enthusiasts. It seems after Kane-Nelson-Woodruff, and the Heule-Nunkesser-Hall paper from Google, academics are not paying as much attention to the practical side.

I would like to cite your work in a book I'm writing, which will include a small section on HyperLogLog. Do you have a preferred citation? I was not able to find a conference or journal that this was published in. Is it accepted for publication in a future conference or journal, by chance? If not, I can refer to arXiv. It would be as follows:

```
@Article{Ertl17,
  author  = {Ertl, Otmar},
  journal = {arXiv preprint arXiv:1706.07290},
  title   = {New Cardinality Estimation Methods for HyperLogLog Sketches},
  year    = {2017},
}
```

And please let me know if there's anything specific you'd like me to include related to your work.

**Comment by oertl** [comment]
Hi Jeremy,

this citation is fine. I have no plans to submit this work elsewhere. However, I have some other related work going on that might be of interest to you. See https://arxiv.org/abs/2101.00314 and the corresponding repository https://github.com/dynatrace-research/set-sketch-paper. I recommend waiting two weeks to read it, as a major revision will be available then.

Otmar

**Comment by j2kun** [comment]
Thanks, Otmar!

**Comment by oertl** [comment]
The major revision of the paper I mentioned before is now available: https://arxiv.org/abs/2101.00314.
